### ISSUE TITLE
interrupting a running script makes the terminal not showing any keyboard input

### ISSUE THREAD

**Issue by lifengjin** [OSC/Open-OnDemand#56]
This has been going on for a while with the OSC OnDemand portal. If I open a terminal on say Pitzer, and run a script, and then Ctrl-C it, there is a high chance for the terminal window to stop displaying any keyboard input at all, showing up as no new letters appearing at the cursor with keyboard pushes. The only way to restore it is to close the browser tab and reopen it. Refreshing the tab does not work.

**Comment by MorganRodgers** [comment]
@lifengjin I suspect that this is specific to your scripts as I can cancel a script without breaking the OnDemand shell application. For example:

```sh
pitzer-login04:~ mrodgers$ cat cancelable.py 
#!/usr/bin/env python
from threading import Event
for i in range(100):
        print(i)
        Event().wait(1)
print('Finished')
pitzer-login04:~ mrodgers$ python cancelable.py 
0
1
2
^CTraceback (most recent call last):
  File "cancelable.py", line 6, in <module>
    Event().wait(1)
  File "/usr/lib64/python2.7/threading.py", line 622, in wait
    self.__cond.wait(timeout, balancing)
  File "/usr/lib64/python2.7/threading.py", line 362, in wait
    _sleep(delay)
KeyboardInterrupt
pitzer-login04:~ mrodgers$ echo 'Terminal still works?'
Terminal still works?
pitzer-login04:~ mrodgers$
```

Can you provide an example of a script that has this problem? Also to help us troubleshoot this issue:

- What web browser are you using?
- Are you using a Mac, Windows or a Linux distribution?

**Comment by ericfranz** [comment]
Another issue is if the output of the program you are running is a lot of text, like can happen when you cat a 40 gigabyte file, is that the terminal app does not allow you to ctrl-c to cancel the stream early, so you have to wait till the entire contents of the file is sent via the cat output. This problem is reported https://github.com/OSC/ood-shell/issues/28. Perhaps the issue you are facing is the same problem.

**Comment by lifengjin** [comment]
The shell does not freeze up. The program gets interrupted as usual, it is just that the shell does not accept keyboard input anymore. You can still do Ctrl-c and it will show ^C, or you can press enter and it will return a new line, but if you just want to type some regular letters or use the arrow keys, nothing will show at the prompt. I also think the problem is somehow triggered by some script, but I don't know what. 
I will test a bit more once I get on a GPU node, as my script is written for GPUs.

**Comment by MorganRodgers** [comment]
If the terminal still accepts input, but does not output what you would expect, and your shell of choice is Bash, then it could be that Bash itself is in an odd state. It may also be worth your while to try the solutions suggested here:

https://unix.stackexchange.com/a/79686/204548

**Comment by treydock** [comment]
Sometimes this happens to me if a program breaks bash and what I do is type `reset` and press enter and then all is fixed.  Worth a shot.  You won't see the text `reset`.  If your unsure anything else is in prompt then do `CTRL+C` then `reset` then press enter and see if your able to see text input after that.

**Comment by lifengjin** [comment]
Thanks. I will try it next time it happens.

On a different note, the deployed version of OnDemand at OSC has the Time Used by Active Jobs in seconds, but it used to be in a more readable format, like in hh:mm:ss. Is it going to be changed back?

**Comment by MorganRodgers** [comment]
There is now an issue tracking the `Time Used` bug: https://github.com/OSC/ood-activejobs/issues/181.
